repos:
  - repo: local
    hooks:
      - id: check-requirements-version
        name: check yq version sync (Makefile vs requirements.in)
        entry: hack/check-requirements-version.sh
        language: script
        pass_filenames: false
        files: (^Makefile$|^requirements\.in$)

  - repo: https://github.com/jazzband/pip-tools
    rev: v7.5.3
    hooks:
      - id: pip-compile
        name: pip-compile (requirements)
        language_version: "3.14"
        args:
          - --allow-unsafe
          - --generate-hashes
          - --output-file=requirements.txt
          - requirements.in
        files: ^requirements\.(in|txt)$


  - repo: local
    hooks:
      - id: uv-pip-compile-build-deps
        name: uv pip compile build deps
        entry: uv pip compile --python-version=3.9 --python-platform=linux
          --generate-hashes
          --output-file=requirements-build.txt
          requirements-build.in
        language: python
        additional_dependencies: [uv]
        files: ^requirements-build\.(in|txt)$
        pass_filenames: false
